using asyncio with ros2 action client
ros2/examples pull request #301
Opened 2021-01-24 19:32 UTC by alemme

I was looking for such an example. Maybe others will find this also useful if they are working with eventloops.

2021-02-11 14:35 UTC, clalancette commented
First, sorry for the delay in looking at this.

Our development process always targets the 'master' branch first, and then we backport to stable distributions if warranted.  So I retargeted the branch to master here, and rebased the code on top of that.  I also ended up doing a small bit of work to fix the style so it conforms to the style tests.  This should now pass CI.

I'm going to do one review pass, looking for any additional issues.  Once that is fixed up, I'm happy to run CI and merge this.  Thanks for the contribution.

2021-02-11 14:41 UTC, clalancette requested changes
There's a bunch of minor things that should be fixed up here, but nothing major.

2021-02-11 14:41 UTC, clalancette commented on rclpy/actions/minimal_action_client/examples_rclpy_minimal_action_client/client_asyncio.py
> +# Copyright 2018 Open Source Robotics Foundation, Inc.
```suggestion
# Copyright 2021 Open Source Robotics Foundation, Inc.
```

2021-02-11 14:41 UTC, clalancette commented on rclpy/actions/minimal_action_client/examples_rclpy_minimal_action_client/client_asyncio.py
> +async def run(args=None, loop=None):
I don't think we need either the `args` argument or the `loop` argument here.  We know for certain they both won't be `None`.

2021-02-11 14:41 UTC, clalancette commented on rclpy/actions/minimal_action_client/examples_rclpy_minimal_action_client/client_asyncio.py
> +        loop = asyncio.get_event_loop()
Similarly, this is just dead code because we are always passing in the `loop`.  Just remove it.

2021-02-11 14:41 UTC, clalancette commented on rclpy/actions/minimal_action_client/examples_rclpy_minimal_action_client/client_asyncio.py
> +    # cancle spinning task
```suggestion
    # cancel spinning task
```

2021-02-11 14:41 UTC, clalancette commented on rclpy/actions/minimal_action_client/examples_rclpy_minimal_action_client/client_asyncio.py
> +    print('unfinished:', len(unfinished))
To make this more consistent with the other printouts, you can do:

```
rclpy.logging.get_logger('minimal_action_client').info(f'unfinished: {unfinished}')
```

Same goes for the other prints below.

2021-02-11 14:41 UTC, clalancette commented on rclpy/actions/minimal_action_client/examples_rclpy_minimal_action_client/client_asyncio.py
> +        super().__init__('minimal_action_client')
```suggestion
        super().__init__('minimal_action_client_asyncio')
```

2021-02-11 14:41 UTC, clalancette commented on rclpy/actions/minimal_action_client/examples_rclpy_minimal_action_client/client_asyncio.py
> +class MinimalActionClient(Node):
```suggestion
class MinimalActionClientAsyncIO(Node):
```

2021-02-12 16:52 UTC, clalancette approved these changes
Looks good to me, thanks for iterating.  I'll run CI on it next.

2021-02-12 16:53 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13655)](http://ci.ros2.org/job/ci_linux/13655/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8534)](http://ci.ros2.org/job/ci_linux-aarch64/8534/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=11370)](http://ci.ros2.org/job/ci_osx/11370/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=13719)](http://ci.ros2.org/job/ci_windows/13719/)

2021-02-12 16:54 UTC, clalancette commented
@alemme Oh, you have to go back and sign your commits to pass the DCO bot.  Once that is done (and CI comes back clean), I can merge this.

2021-02-12 18:45 UTC, alemme commented
Thanks for the review. Commits should be in order now :)

2021-02-12 18:48 UTC, clalancette commented
And CI looks happy.  Thanks for the contribution, merging.

2021-02-12 18:48 UTC, merged