fix: Fixed compilation after API change of TimerBase::execute
ros2/examples pull request #375
Opened 2024-03-22 16:37 UTC by jmachowinski

This is a followup of https://github.com/ros2/rclcpp/pull/2343

2024-03-28 22:42 UTC, fujitatomoya approved these changes
lgtm

2024-03-28 22:46 UTC, fujitatomoya commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=20659)](http://ci.ros2.org/job/ci_linux/20659/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14990)](http://ci.ros2.org/job/ci_linux-aarch64/14990/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21362)](http://ci.ros2.org/job/ci_windows/21362/)

2024-03-29 17:14 UTC, fujitatomoya requested changes

2024-03-29 17:14 UTC, fujitatomoya commented on rclcpp/topics/minimal_subscriber/time_triggered_wait_set_subscriber.cpp
> +                timer_->execute_callback(*data);
Compile error.

```suggestion
                timer_->execute_callback(data);
```

2024-03-29 17:14 UTC, fujitatomoya commented on rclcpp/wait_set/src/wait_set_topics_and_timer.cpp
> +          one_off_timer->execute_callback(*data);
Compile error.

```suggestion
          one_off_timer->execute_callback(data);
```

2024-03-29 19:42 UTC, fujitatomoya approved these changes

2024-03-29 19:49 UTC, fujitatomoya commented
@jmachowinski i will wait for https://github.com/ros2/rcl/pull/1142.

and then, i will start the CI with https://github.com/ros2/rclcpp/pull/2343(https://gist.githubusercontent.com/fujitatomoya/abec3a5908d5af11b95982106feace2c/raw/1b865510acff5b3d4fa57e81b45523b2d2c59b9d/ros2.repos)

CC: @clalancette @mjcarroll @wjwwood @alsora

2024-04-05 15:56 UTC, fujitatomoya commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=20761)](http://ci.ros2.org/job/ci_linux/20761/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15060)](http://ci.ros2.org/job/ci_linux-aarch64/15060/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21440)](http://ci.ros2.org/job/ci_windows/21440/)

2024-04-12 12:29 UTC, mjcarroll approved these changes

2024-04-12 12:29 UTC, merged